project_name: traefik-kop
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./bin/traefik-kop/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      ["ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      ["ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-armv6"]
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      ["ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-armv7"]
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      ["ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jittering/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/jittering/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/jittering/{{ .ProjectName }}:{{ .Version }}-arm64v8
